version: '3.9'

services:
  database:
    image: postgres
    container_name: name
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
